# Generated by Django 3.1.7 on 2021-03-12 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 3, 12, 4, 49, 26, 203473, tzinfo=utc), max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
