# Generated by Django 3.1.7 on 2021-04-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=255, null=True),
        ),
    ]
