# Generated by Django 3.1.7 on 2021-03-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchases_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
    ]
