# Generated by Django 3.1.7 on 2021-03-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20210310_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
