# Generated by Django 3.1.7 on 2021-03-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchases_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
