# Generated by Django 3.1.7 on 2021-03-12 04:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_auto_20210312_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 3, 12, 4, 37, 57, 871391, tzinfo=utc), max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
