# Generated by Django 3.1.7 on 2021-03-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_auto_20210312_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='bought_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
