# Generated by Django 3.1.7 on 2021-03-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_auto_20210312_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=255, null=True),
        ),
    ]
