# Generated by Django 3.1.7 on 2021-03-26 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_auto_20210312_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 14, 52, 17, 600082)),
            preserve_default=False,
        ),
    ]
