# Generated by Django 3.1.7 on 2021-03-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_purchases_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='timestamp',
            new_name='datetime',
        ),
    ]
