# Generated by Django 3.1.7 on 2021-03-26 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_auto_20210326_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='datetime',
        ),
        migrations.AddField(
            model_name='purchases',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 15, 1, 44, 136645)),
            preserve_default=False,
        ),
    ]
