# Generated by Django 3.1.7 on 2021-04-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0015_auto_20210326_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
    ]
