# Generated by Django 3.1.7 on 2021-04-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_purchases_pending_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='pending_amount',
        ),
    ]
