# Generated by Django 3.1.7 on 2021-04-01 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_purchases_pending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalamount',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchases'),
        ),
    ]
