# Generated by Django 3.1.7 on 2021-04-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_totalamount_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalamount',
            name='model',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchases'),
        ),
    ]
