# Generated by Django 3.1.7 on 2021-04-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0022_auto_20210401_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalamount',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchases'),
        ),
    ]
